Fix ip output
techservicesillinois/SecOps-Powershell-Qualys pull request #48
Opened 2021-11-23 20:30 UTC by baristaTam

## [1.4.3] - 2021-11-23

### Changed

- IP logic in Get-QualysAssetGroups sometimes resulted in a string being returned instead of a string array for the IPs property

2021-11-23 20:37 UTC, mabaumgartner approved these changes

2021-11-24 14:53 UTC, mabaumgartner submitted a review, later dismissed

2021-11-29 15:29 UTC, edthedev commented on src/UofIQualys/functions/public/Get-QualysAssetGroups.ps1
> +            $AssetGroupIDs = $Response.ASSET_GROUP_LIST_OUTPUT.RESPONSE.ASSET_GROUP_LIST.ASSET_GROUP.ID
```suggestion
$AssetGroups = $Response.ASSET_GROUP_LIST_OUTPUT.RESPONSE.ASSET_GROUP_LIST.ASSET_GROUP
```

2021-11-29 15:30 UTC, edthedev commented on src/UofIQualys/functions/public/Get-QualysAssetGroups.ps1
> +            foreach ($ID in $AssetGroupIDs) {
```suggestion
foreach ($ID in $AssetGroups.ID) {
```

2021-11-29 15:30 UTC, edthedev commented on src/UofIQualys/functions/public/Get-QualysAssetGroups.ps1
>                  If($Response.ASSET_GROUP_LIST_OUTPUT.RESPONSE.ASSET_GROUP_LIST.ASSET_GROUP.IP_SET[$Index].IP_RANGE){
```suggestion
If($AssetGroups.IP_SET[$Index].IP_RANGE){
```

and then we can make this change for each of the `if` lines below as well.

2021-11-29 15:32 UTC, edthedev commented on src/UofIQualys/functions/public/Get-QualysAssetGroups.ps1
>                      If($Response.ASSET_GROUP_LIST_OUTPUT.RESPONSE.ASSET_GROUP_LIST.ASSET_GROUP.IP_SET[$Index].IP){
```suggestion
If($AssetGroups.IP_SET[$Index].IP){
```

2021-11-29 15:32 UTC, edthedev requested changes
I would like to see the change I suggested below made to increase readability.

2021-12-01 17:07 UTC, edthedev approved these changes

2021-12-01 17:14 UTC, mabaumgartner approved these changes

2021-12-01 17:14 UTC, merged